### ISSUE TITLE
Missing Tag Constants

### ISSUE THREAD

**Issue by beberlei** [Wikia/opentracing-php#3]
The Go library includes an extension namespace with predefined tags, this should be available as static class:

https://github.com/opentracing/opentracing-go/blob/master/ext/tags.go

``` php
namespace OpenTracing;

class Tags
{
    const PEER_SERVICE = 'peer.service';
    const PEER_HOSTNAME = 'peer.hostname';
    //...
}
```

Can be used with:

``` php
$span->setTag(Tags::PEER_SERVICE, 'foobar');
```

**Comment by wladekb** [comment]
@beberlei are dots allowed tags/attributes? If any implementation would like to send them as HTTP headers that would add an extra effort to encode those within the header name.

**Comment by beberlei** [comment]
@wladekb they are defined with dots in the go and python implementations. Yeah as HTTP header they need translation, maybe we should raise that as an issue on the global OT tracker?

**Comment by wladekb** [comment]
Filed as https://github.com/opentracing/opentracing.github.io/issues/68

**Comment by beberlei** [comment]
Oh of course, Tags are not part of HTTP headers, so dots are allowed :-)

This ticket is done, except the missing tag `span.kind` and its values `c` or `s`:

```
const SPAN_KIND = 'span.kind';
const SPAN_KIND_RPC_SERVER = 's';
const SPAN_KIND_RPC_CLIENT = 'c';
```

**Comment by wladekb** [comment]
Done.
